/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Libro;
import clases.Vehiculo;
import gestion.GestionLibro;
import java.awt.SystemColor;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import gestion.GestionVehiculo;
/**
 *
 * @author ProfL3301
 */
public class frmMantenimientoVehiculo extends javax.swing.JFrame {

     private DefaultTableModel modelo;
     private GestionVehiculo gestionVehiculo;
      
    /**
     * Creates new form frmMantenimientosLibros
     */
        public frmMantenimientoVehiculo(GestionVehiculo gestionVehiculo) {
        initComponents();
        getContentPane().setBackground(SystemColor.activeCaption);

        modelo = new DefaultTableModel();
        modelo.addColumn("Modelo");
        modelo.addColumn("Cliente");
        modelo.addColumn("Empleado");
        modelo.addColumn("Promoción");
        tbVehiculo.setModel(modelo); // la tabla todavía se llama tbLibro, no pasa nada

        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.gestionVehiculo = gestionVehiculo;

        listarVehiculos();
    }

    
        void listarVehiculos() {
        modelo.setNumRows(0);

        for (int i = 0; i < gestionVehiculo.obtenerTotalVehiculos(); i++) {
            Vehiculo v = gestionVehiculo.obtenerVehiculos()[i];
            if (v != null) {
                Object[] fila = {
                    v.getVehiculo(),      // modelo / nombre del vehículo
                    v.getCliente(),      // cliente
                    v.getEmpleado(),     // empleado
                    v.getPromocion()    // monto de la promoción / precio
                };
                modelo.addRow(fila);
            }
        }
    }

    void limpiar() {
        txtmodeloVehiculo.setText("");   // aquí usaremos Código = Modelo
        txtcliente.setText("");   // Título = Cliente
        txtempleado.setText("");    // Autor  = Empleado
        txtpromocion.setText("");   // Precio = Promoción
        txtmodeloVehiculo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmodeloVehiculo = new javax.swing.JLabel();
        lblcliente = new javax.swing.JLabel();
        lblempleado = new javax.swing.JLabel();
        lblpromocion = new javax.swing.JLabel();
        txtmodeloVehiculo = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtempleado = new javax.swing.JTextField();
        txtpromocion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVehiculo = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento de Libros");

        lblmodeloVehiculo.setText("modeloVehiculo");

        lblcliente.setText("cliente");

        lblempleado.setText("empleado");

        lblpromocion.setText("promocion");

        tbVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbVehiculo);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal_93488.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_rotation_icon_154664.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove_bin_icon-icons.com_72400.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmodeloVehiculo)
                            .addComponent(lblcliente)
                            .addComponent(lblempleado)
                            .addComponent(lblpromocion))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtempleado, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(txtcliente)
                            .addComponent(txtmodeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnRegistrar)
                        .addGap(26, 26, 26)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodeloVehiculo)
                    .addComponent(txtmodeloVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcliente)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblempleado)
                    .addComponent(txtempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpromocion)
                    .addComponent(txtpromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String modeloVehiculo =txtmodeloVehiculo.getText().trim();
        String cliente = txtcliente.getText().trim();
        String empleado = txtempleado.getText().trim();
        double promocion = Double.parseDouble(txtpromocion.getText().trim());
        
        //Instanciamos
        Vehiculo vehiculo = new Vehiculo(modeloVehiculo, cliente, empleado, promocion);
        
        if (gestionVehiculo.actualizar(vehiculo)) {
            listarVehiculos();
            limpiar();
            
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo registrar vehiculo");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         
        String modeloVehiculo =txtmodeloVehiculo.getText().trim();
        String cliente = txtcliente.getText().trim();
        String empleado = txtempleado.getText().trim();
        double promocion = Double.parseDouble(txtpromocion.getText().trim());
        
        //Instanciamos
        Vehiculo vehiculo=new Vehiculo(modeloVehiculo, cliente, empleado, promocion);
        
        
        if( gestionVehiculo.actualizar(vehiculo)){
            listarVehiculos(); 
            JOptionPane.showMessageDialog(this, " Vehiculo actualizado");
        }else{
            JOptionPane.showMessageDialog(this, " No se encontro el vehiculo a actualizar");
        } 
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String modeloVehiculo=txtmodeloVehiculo.getText().trim();
        if(gestionVehiculo.eliminar(modeloVehiculo)){
            listarVehiculos();
            limpiar();
            JOptionPane.showMessageDialog(this, "Vehiculo eliminado");
        }else{
             JOptionPane.showMessageDialog(this, "No se encontro el vehiculo a eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoVehiculo(new GestionVehiculo()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcliente;
    private javax.swing.JLabel lblempleado;
    private javax.swing.JLabel lblmodeloVehiculo;
    private javax.swing.JLabel lblpromocion;
    private javax.swing.JTable tbVehiculo;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtempleado;
    private javax.swing.JTextField txtmodeloVehiculo;
    private javax.swing.JTextField txtpromocion;
    // End of variables declaration//GEN-END:variables
}
