/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import gestion.GestionVehiculo;
import javax.swing.UIManager;
import utilitario.EscritorioPersonalizado;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicMenuBarUI;
import java.awt.Dimension;
import java.awt.GradientPaint;


/**
 *
 * @author ProfL3301
 */
public class frmPrincipal extends javax.swing.JFrame {
 
 //Variables globales
 private EscritorioPersonalizado escritorio;
 private GestionVehiculo gestionVehiculo = new GestionVehiculo();
 
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
    initComponents();
    setTitle(".: Sistema de Gestión de Vehículos :.");

    escritorio = new EscritorioPersonalizado();
    this.setContentPane(escritorio);

    // ... (todo tu código de colores del menú)
    
     // --- (2) Quitar borde gris del menu ---
    menuBar.setBorder(null);
    
    menuBar.setBackground(new Color(230, 184, 0));
    
        // --- (3) Hacer la barra más gruesa (más moderna) ---
    menuBar.setPreferredSize(new Dimension(menuBar.getWidth(), 40));
    
    // Pintamos nosotros mismos el fondo del menú
    menuBar.setUI(new BasicMenuBarUI() {
    @Override
    public void paint(Graphics g, JComponent c) {
        Graphics2D g2 = (Graphics2D) g.create();

        GradientPaint gp = new GradientPaint(
            0, 0, new Color(255, 215, 0), 
            0, c.getHeight(), new Color(230, 184, 0)
        );

        g2.setPaint(gp);
        g2.fillRect(0, 0, c.getWidth(), c.getHeight());
        g2.dispose();
    }
});
        // 🔹 AQUÍ CAMBIAS LOS LABELS DEL MENÚ
    mnMantenimiento.setText("Vehículos");
    mnitmMantenimientoLibro.setText("Mantenimiento de Vehículos");

    mnConsultas.setText("Consultas");
    mnitmConsultarLibro.setText("Consultar Vehículo");

    mnReportes.setText("Reportes");  // si quieres: "Reportes de Ventas"
    mnSalir.setText("Salir");

    mnMantenimiento.setForeground(Color.BLACK);
    mnConsultas.setForeground(Color.BLACK);
    mnReportes.setForeground(Color.BLACK);
    mnSalir.setForeground(Color.BLACK);


    mnMantenimiento.setForeground(Color.BLACK);
    mnConsultas.setForeground(Color.BLACK);
    mnReportes.setForeground(Color.BLACK);
    mnSalir.setForeground(Color.BLACK);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnMantenimiento = new javax.swing.JMenu();
        mnitmMantenimientoLibro = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mnitmConsultarLibro = new javax.swing.JMenuItem();
        mnReportes = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: Sistema de Gestión de Libros :.");

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        mnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        mnMantenimiento.setText("Mantenimiento");

        mnitmMantenimientoLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        mnitmMantenimientoLibro.setText("Mantenimiento de Libros");
        mnitmMantenimientoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmMantenimientoLibroActionPerformed(evt);
            }
        });
        mnMantenimiento.add(mnitmMantenimientoLibro);

        menuBar.add(mnMantenimiento);

        mnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        mnConsultas.setText("Consultas");

        mnitmConsultarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        mnitmConsultarLibro.setText("Consultar Libro");
        mnitmConsultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmConsultarLibroActionPerformed(evt);
            }
        });
        mnConsultas.add(mnitmConsultarLibro);

        menuBar.add(mnConsultas);

        mnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        mnReportes.setText("Reportes");
        menuBar.add(mnReportes);

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        mnSalir.setText("Salir");
        mnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSalirMouseClicked(evt);
            }
        });
        menuBar.add(mnSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSalirMouseClicked

    private void mnitmMantenimientoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmMantenimientoLibroActionPerformed
        // TODO add your handling code here:
    frmMantenimientoVehiculo frm = new frmMantenimientoVehiculo(gestionVehiculo);
    frm.setLocationRelativeTo(null);
    frm.setVisible(true);
 
    }//GEN-LAST:event_mnitmMantenimientoLibroActionPerformed

    private void mnitmConsultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmConsultarLibroActionPerformed
        // TODO add your handling code here:
    frmConsultarVehiculo frm = new frmConsultarVehiculo(gestionVehiculo);
    frm.setLocationRelativeTo(null);
    frm.setVisible(true);
        
    }//GEN-LAST:event_mnitmConsultarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

  

        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPrincipal frm = new frmPrincipal();
                frm.setExtendedState(MAXIMIZED_BOTH);
                frm.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnMantenimiento;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenuItem mnitmConsultarLibro;
    private javax.swing.JMenuItem mnitmMantenimientoLibro;
    // End of variables declaration//GEN-END:variables
}
